# Generated by Django 4.1.1 on 2022-09-07 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drugstore',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('drugstore_id', models.CharField(max_length=75, primary_key=True, serialize=False, verbose_name='Идентификатор аптеки')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Аптека',
                'verbose_name_plural': 'Аптеки',
                'ordering': ['drugstore_id'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_open', models.TimeField(blank=True, verbose_name='Понедельник открытие')),
                ('monday_close', models.TimeField(verbose_name='Понедельник закрытие')),
                ('tuesday_open', models.TimeField(blank=True, verbose_name='Вторник открытие')),
                ('tuesday_close', models.TimeField(verbose_name='Вторник закрытие')),
                ('wednesday_open', models.TimeField(blank=True, verbose_name='Среда открытие')),
                ('wednesday_close', models.TimeField(verbose_name='Среда закрытие')),
                ('thursday_open', models.TimeField(blank=True, verbose_name='Четверг открытие')),
                ('thursday_close', models.TimeField(verbose_name='Четверг закрытие')),
                ('friday_open', models.TimeField(blank=True, verbose_name='Пятница открытие')),
                ('friday_close', models.TimeField(verbose_name='Пятница закрытие')),
                ('saturday_open', models.TimeField(blank=True, verbose_name='Суббота открытие')),
                ('saturday_close', models.TimeField(verbose_name='Суббота закрытие')),
                ('sunday_open', models.TimeField(blank=True, verbose_name='Воскресенье открытие')),
                ('sunday_close', models.TimeField(verbose_name='Воскресенье закрытие')),
                ('drugstore', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='drugstores.drugstore', verbose_name='Аптека')),
            ],
            options={
                'verbose_name': 'Расписание аптеки',
                'verbose_name_plural': 'Расписание аптек',
                'ordering': ['drugstore'],
            },
        ),
    ]
