# Generated by Django 4.1.1 on 2022-09-07 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugstores', '0002_drugstore_created_at_drugstore_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_open', models.CharField(max_length=5, verbose_name='Понедельник открытие')),
                ('monday_close', models.CharField(max_length=5, verbose_name='Понедельник закрытие')),
                ('tuesday_open', models.CharField(max_length=5, verbose_name='Вторник открытие')),
                ('tuesday_close', models.CharField(max_length=5, verbose_name='Вторник закрытие')),
                ('wednesday_open', models.CharField(max_length=5, verbose_name='Среда открытие')),
                ('wednesday_close', models.CharField(max_length=5, verbose_name='Среда закрытие')),
                ('thursday_open', models.CharField(max_length=5, verbose_name='Четверг открытие')),
                ('thursday_close', models.CharField(max_length=5, verbose_name='Четверг закрытие')),
                ('friday_open', models.CharField(max_length=5, verbose_name='Пятница открытие')),
                ('friday_close', models.CharField(max_length=5, verbose_name='Пятница закрытие')),
                ('saturday_open', models.CharField(max_length=5, verbose_name='Суббота открытие')),
                ('saturday_close', models.CharField(max_length=5, verbose_name='Суббота закрытие')),
                ('sunday_open', models.CharField(max_length=5, verbose_name='Воскресенье открытие')),
                ('sunday_close', models.CharField(max_length=5, verbose_name='Воскресенье закрытие')),
                ('drugstore', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='drugstores.drugstore', verbose_name='Аптека')),
            ],
            options={
                'verbose_name': 'Расписание аптеки',
                'verbose_name_plural': 'Расписание аптек',
                'ordering': ['drugstore'],
            },
        ),
    ]
