# Generated by Django 4.1.1 on 2022-09-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugstores', '0003_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='friday_open',
            field=models.CharField(blank=True, max_length=5, verbose_name='Пятница открытие'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='monday_open',
            field=models.CharField(blank=True, max_length=5, verbose_name='Понедельник открытие'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='saturday_open',
            field=models.CharField(blank=True, max_length=5, verbose_name='Суббота открытие'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sunday_open',
            field=models.CharField(blank=True, max_length=5, verbose_name='Воскресенье открытие'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='thursday_open',
            field=models.CharField(blank=True, max_length=5, verbose_name='Четверг открытие'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tuesday_open',
            field=models.CharField(blank=True, max_length=5, verbose_name='Вторник открытие'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wednesday_open',
            field=models.CharField(blank=True, max_length=5, verbose_name='Среда открытие'),
        ),
    ]
