# Generated by Django 4.1.1 on 2022-09-08 08:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('drugstores', '0003_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugstore',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drugstore', to='drugstores.region', verbose_name='Регион аптеки'),
        ),
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
