# Generated by Django 4.1.1 on 2022-09-08 17:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('drugstores', '0004_drugstore_region_alter_region_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Город')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='drugstores.region', verbose_name='Регион города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес аптеки')),
                ('location_lat', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Широта')),
                ('location_lon', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Долгота')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugstores', to='drugstores.city', verbose_name='Город аптеки')),
                ('drugstore', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geo', to='drugstores.drugstore', verbose_name='Аптека')),
            ],
        ),
    ]
